name: CI

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: { node: [18, 20, 22] }
    
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test

  check-secrets:
    runs-on: ubuntu-latest
    outputs:
      has_secrets: ${{ steps.verify.outputs.has_secrets }}
    steps:
      - name: Verify Docker Hub secrets presence
        id: verify
        env:
          USER:  ${{ secrets.DOCKERHUB_USERNAME }}
          PASS:  ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          if [[ -n "$USER" && ( -n "$PASS"  ) ]]; then
            echo "has_secrets=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_secrets=false" >> "$GITHUB_OUTPUT"
          fi

  integration:
    needs: [build-and-test, check-secrets]
    if: needs.check-secrets.outputs.has_secrets == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: pnpm }
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - name: Smoke (Hub/Registry)
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          node -e "console.log('Integration placeholder OK')"
 